projects:
  Codegen Frontend:
    schemaPath: schema.graphql
    includes:
      - ../frontend/src/api/**/*.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ../frontend/src/API.ts
        docsFilePath: ../frontend/src/api
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: react
        maxDepth: 5
  Codegen Backend:
    schemaPath: schema.graphql
    includes:
      - ./lambdas/api/types/**/*.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        docsFilePath: ./lambdas/api/types
        generatedFileName: ./lambdas/api/types.ts
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: null
        maxDepth: 5
extensions:
  amplify:
    version: 3
